apiVersion: v1
kind: Service
metadata:
  labels:
    {{ $.Values.app.group }}/app-name: {{ $.Values.app.name }}
    {{ $.Values.app.group }}/is-isolated-run: "false"
    {{- range $i, $label := $deployment.labels }}
    {{ $label.name }}: {{ $label.value }}
    {{- end }}
  name: app-{{ $.Values.app.name }}
spec:
  type: ClusterIP
  ports:
  {{ $process.servicePorts | toYaml | indent 4 }}
selector:
  {{ $.Values.app.group }}/app-name: {{ $.Values.app.name }}
  {{ $.Values.app.group }}/app-process: {{ $.Values.app.Service.ProcessName }}
  {{ $.Values.app.group }}/app-deployment-version: {{ $.Values.app.Service.Version | quote }}
  {{ $.Values.app.group }}/is-isolated-run: "false"