stages:
  - test
  - build

sudo: required

jobs:
  include:
    - stage: test
      name: "Running unit tests"
      language: go
      go: "1.17"
      script:
        - make install-kubebuilder KUBEBUILDER_INSTALL_DIR=/tmp/bin KUBEAPI_SERVER_INSTALL_DIR=/tmp/bin KUBECTL_INSTALL_DIR=/tmp/bin KUBECTL_INSTALL_DIR=/tmp ETCD_INSTALL_DIR=/tmp/bin
        - export PATH="/tmp/bin:$PATH"
        - make test

    - stage: build
      if: type == pull_request
      branches:
        except:
          - master
      language: bash
      sudo: required
      script:
        - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
        - docker build -t shipasoftware/ketch:$TRAVIS_COMMIT .
        - docker push shipasoftware/ketch:$TRAVIS_COMMIT

    - stage: test
      sudo: required
      name: "Running integration tests"
      language: go
      go: 1.17.x
      services:
        - docker
      provider: script
      script:
        - bash cli_tests/install_kubectl.sh
        - bash cli_tests/install_minikube.sh
        - bash cli_tests/install_bats.sh
        - bash cli_tests/install_ketch.sh
        - bats cli_tests/app.sh
        - bats cli_tests/job.sh